using System;
using System.Windows;
using System.Windows.Controls;

namespace MSC_WPF_BETA
{
    /// <summary>
    /// Interaction logic for PrintWindow.xaml
    /// </summary>
    public partial class PrintWindow : Window
    {
        public PrintWindow()
        {
            InitializeComponent();  
            //Initial code to load all the details during page load
            if (Dashboard.printFormNo == "1")
            {
                PrintGrid1.Visibility = Visibility.Visible;
                vendorNamePrintLabel.Content = Dashboard.vendorName;
                vendorAddressPrintLabel.Content = Dashboard.vendorAddress;
                accNoPrintLabel.Content = "Account No: " + Dashboard.vendorAccNo;
                bankNamePrintLabel.Content = "Bank: " + Dashboard.vendorBankName;
                branchNamePrintLabel.Content = "Branch: " + Dashboard.vendorBranchName;
                recentdateLabel.Content = DateTime.Now.Date;
                natureofworkPrintLabel.Content = Dashboard.natureofwork;
                paymentDatePrintLabel.Content = Dashboard.payment_date;
                remarksPrintLabel.Content = "Remarks: " + Dashboard.remarks;
                generatedByPrintLabel.Content = "Generated by " + MainWindow.fullName + ", North Bengal University";
                receiptNoLabel.Content = Dashboard.emId;
                tendorNoPrintLabel.Content = Dashboard.tenderno;
                estimatedCostPrintLabel.Content = "₹ " + Dashboard.estimatedCost;
                earnestmoneyPrintLabel.Content = "₹ " + Dashboard.earnestMoney;
                paymentbalancePrintLabel.Content = "₹ " + Dashboard.earnestMoney;
            } else
            {
                PrintGrid2.Visibility = Visibility.Visible;
                vendorNamePrintLabel2.Content = Dashboard.vendorName;
                vendorAddressPrintLabel2.Content = Dashboard.vendorAddress;
                accNoPrintLabel2.Content = "Account No: " + Dashboard.vendorAccNo;
                bankNamePrintLabel2.Content = "Bank: " + Dashboard.vendorBankName;
                branchNamePrintLabel2.Content = "Branch: " + Dashboard.vendorBranchName;
                recentdateLabel2.Content = DateTime.Now.Date;
                natureofworkPrintLabel2.Content = Dashboard.natureofwork;
                paymentDatePrintLabel2.Content = Dashboard.payment_date;
                remarksPrintLabel2.Content = "Remarks: " + Dashboard.remarks;
                generatedByPrintLabel2.Content = "Generated by " + MainWindow.fullName + ", North Bengal University";
                receiptNoLabel2.Content = Dashboard.sdId;
                billNoPrintLabel.Content = Dashboard.billno;
                securityDepositPrintLabel.Content = "₹ " + Dashboard.securityDeposit;
                paymentbalancePrintLabel2.Content = "₹ " + Dashboard.securityDeposit;
            }
        }

        //Event to print the select grid visuals
        private void PrintButton_Click(object sender, RoutedEventArgs e)
        {
            if (Dashboard.printFormNo == "1")
            {
                PrintDialog myPrintDialog = new PrintDialog();
                if (myPrintDialog.ShowDialog() == true)
                {
                    myPrintDialog.PrintVisual(PrintGrid1, "Print");
                }
            } else
            {
                PrintDialog myPrintDialog = new PrintDialog();
                if (myPrintDialog.ShowDialog() == true)
                {
                    myPrintDialog.PrintVisual(PrintGrid2, "Print");
                }
            }

        }
    }
}
